# Generated by Django 5.2.13 on 2026-05-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=64, unique=True, verbose_name="identifiant URL"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "badge",
                    models.CharField(
                        max_length=120, verbose_name="pastille (ex. Atelier · Niveau 2)"
                    ),
                ),
                (
                    "level_label",
                    models.CharField(
                        max_length=80, verbose_name="niveau (carte accueil)"
                    ),
                ),
                ("summary", models.TextField(verbose_name="résumé (carte accueil)")),
                ("tagline", models.CharField(max_length=300)),
                ("pitch", models.TextField()),
                (
                    "tone",
                    models.CharField(
                        choices=[("sky", "Ciel"), ("mint", "Menthe")],
                        default="sky",
                        max_length=10,
                    ),
                ),
                (
                    "schedule_time",
                    models.CharField(max_length=80, verbose_name="horaires affichés"),
                ),
                (
                    "dates_text",
                    models.CharField(max_length=200, verbose_name="dates des séances"),
                ),
                (
                    "location",
                    models.CharField(
                        default="Paris 13e", max_length=120, verbose_name="lieu"
                    ),
                ),
                (
                    "max_students",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="places max"
                    ),
                ),
                (
                    "sessions_count",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="nombre de séances"
                    ),
                ),
                (
                    "price_display",
                    models.CharField(
                        default="175 € (25 €/séance)",
                        max_length=120,
                        verbose_name="tarif affiché",
                    ),
                ),
                (
                    "program_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Vide = texte par défaut à partir du nombre de séances.",
                        max_length=200,
                        verbose_name="sous-titre du programme",
                    ),
                ),
                (
                    "highlight_title",
                    models.CharField(
                        blank=True,
                        help_text="Ex. « Objectif final » sous les infos pratiques.",
                        max_length=120,
                        verbose_name="titre encadré optionnel",
                    ),
                ),
                (
                    "highlight_text",
                    models.TextField(
                        blank=True, verbose_name="texte encadré optionnel"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="meta description"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "atelier",
                "verbose_name_plural": "ateliers",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="workshops.workshop",
                        verbose_name="atelier",
                    ),
                ),
            ],
            options={
                "verbose_name": "séance (programme)",
                "verbose_name_plural": "séances (programme)",
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
